
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pavit
 */
public class Dbframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form Dbframe
     */
    public Dbframe() {
        initComponents();
    
    try{        
   Class.forName("org.apache.derby.jdbc.ClientDriver");
    Connection connection=DriverManager.getConnection("jdbc:derby://localhost:1527/accountantdetails", "pavi", "pavi");
    JOptionPane.showMessageDialog(null, "connected successfully");
    Statement st=connection.createStatement();
        ResultSet r=st.executeQuery("select *from accdet2");
        ResultSetMetaData rm=r.getMetaData();
        int columns=rm.getColumnCount();
        DefaultTableModel dt=new DefaultTableModel();
        Vector column=new Vector();
        Vector row=new Vector();
        for(int i=1;i<=columns;i++){
            column.addElement(rm.getColumnName(i));
        }
         dt.setColumnIdentifiers(column);
         while(r.next()){
             row=new Vector();
             for(int j=1;j<=columns;j++){
                 row.addElement(r.getString(j));}
            
          dt.addRow(row);
       
        
    }
    jTable2.setModel(dt);
            }
    catch(ClassNotFoundException|SQLException e)
    {     
        e.printStackTrace();
        System.out.println("error"+e);
        
    }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Dbframe");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
